/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author fajriyan nur
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form Produk
     */
    public LOGIN() {
        initComponents();
        Koneksi_DB();
        closefrem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MASUK = new javax.swing.JButton();
        DAFTAR = new javax.swing.JButton();
        EMAIL = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        MASUK.setText("MASUK");
        MASUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASUKActionPerformed(evt);
            }
        });

        DAFTAR.setText("DAFTAR");
        DAFTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAFTARActionPerformed(evt);
            }
        });

        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EMAIL)
                            .addComponent(PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DAFTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MASUK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(MASUK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DAFTAR)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MASUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASUKActionPerformed
    if (log()){
        JOptionPane.showMessageDialog(null, "LOGIN BENAR");
        try {
            String sql1 = "select status from login where status=1 AND user='"+EMAIL.getText()+"'";
            hasil = stmt.executeQuery(sql1);
            while (hasil.next()){
                JOptionPane.showMessageDialog(null, "ADMIN");
                closefrem();
                MASUK1 masuk = new MASUK1();
                masuk.setVisible(rootPaneCheckingEnabled);
            }
            String sql2 = "select status from login where status=2 AND user='"+EMAIL.getText()+"'";
            hasil = stmt.executeQuery(sql2);
            while (hasil.next()){
                JOptionPane.showMessageDialog(null, "USER");
                closefrem();
                MASUK1 masuk = new MASUK1();
                masuk.setVisible(rootPaneCheckingEnabled);
            }
            String sql3 = "select status from login where status=3 AND user='"+EMAIL.getText()+"'";
            hasil = stmt.executeQuery(sql3);
            while (hasil.next()){
                JOptionPane.showMessageDialog(null, "MODERATOR");
            }
        } catch (Exception e) {
        }
    }else{
        JOptionPane.showMessageDialog(null, "LOGIN SALAH");
    }
    }//GEN-LAST:event_MASUKActionPerformed

    private void DAFTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAFTARActionPerformed
        closefrem();
        DAFTAR daftar = new DAFTAR();
        daftar.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_DAFTARActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed
    
    /**
     * @param args the command line arguments
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String URL_DB = "jdbc:mysql://localhost/uap-java-web";
    static final String username_db = "root";
    static final String password_db = "";
    static String sql,us,aaa,idd;
    
   
    static Connection conn;
    static Statement stmt;
    public PreparedStatement ps;
    static ResultSet hasil;
    static Scanner in = new Scanner (System.in);
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }
     static void Koneksi_DB(){
        try {
            Class.forName(JDBC_DRIVER);
            conn = (Connection) DriverManager.getConnection(URL_DB,username_db,password_db);
            stmt = (Statement) conn.createStatement();
            System.out.println("--- KONEKSI BERHASIL ---");
        } catch (Exception e) {
            System.out.println("--- KONEKSI GAGAL ---\n"+e);
        }
    }
     private boolean log() {
        boolean kondisi;
            try {
            kondisi = false; 
            String sql = "select * from login where user='"+EMAIL.getText()+"'AND pass='"+PASSWORD.getText()+"'";
            hasil = stmt.executeQuery(sql);
            while (hasil.next()){
                String sql15= "UPDATE login set last_login=now() where user='"+EMAIL.getText()+"'";
                    PreparedStatement up = conn.prepareStatement(sql15);
                    up.execute();
                kondisi = true;
                
            }
        } catch (Exception e) {
            kondisi = false;
            
        }
            return kondisi;
    }
     
       public void closefrem (){
           super.dispose();
       }
       
       
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DAFTAR;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JButton MASUK;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
